import { v4 as id } from 'uuid';

export const fakeData = [
  {
    category: 'Category1',
    questions: [
      {
        id: 1,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 2,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 3,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 4,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 5,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 6,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'Category2',
    questions: [
      {
        id: 7,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 8,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 9,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 10,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 11,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 12,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'Category3',
    questions: [
      {
        id: 13,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 14,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 15,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 16,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 17,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 18,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'Category4',
    questions: [
      {
        id: 19,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 20,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 21,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 22,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 23,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 24,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'Category5',
    questions: [
      {
        id: 25,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 26,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 27,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 28,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 29,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 30,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'Category6',
    questions: [
      {
        id: 31,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 32,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 33,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 34,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 35,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 36,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
];
