export const roundOne = [
  {
    category: '5-LETTER COUNTRIES',
    questions: [
      {
        id: 1,
        value: 100,
        question: 'It stretches southward to Cape Horn',
        answers: ['Chile', 'China', 'Spain', 'Egypt'],
        correct_answer: 'Chile',
      },
      {
        id: 2,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 3,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 4,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 5,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 6,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: '20TH CENTURY ENGLISH',
    questions: [
      {
        id: 7,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 8,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 9,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 10,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 11,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 12,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'QUOTABLE WOMEN',
    questions: [
      {
        id: 13,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 14,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 15,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 16,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 17,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 18,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'ABANDONED PLACES',
    questions: [
      {
        id: 19,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 20,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 21,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 22,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 23,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 24,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'GESTURES',
    questions: [
      {
        id: 25,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 26,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 27,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 28,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 29,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 30,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'DIFFER BY A LETTER',
    questions: [
      {
        id: 31,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 32,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 33,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 34,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 35,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 36,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
];

export const roundTwo = [
  {
    category: 'ROUND TWO ROUND TWO 1 ',
    questions: [
      {
        id: 37,
        value: 100,
        question: 'It stretches southward to Cape Horn',
        answers: ['Chile', 'China', 'Spain', 'Egypt'],
        correct_answer: 'Chile',
      },
      {
        id: 38,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 39,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 40,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 41,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 42,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'ROUND TWO 2',
    questions: [
      {
        id: 43,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 44,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 45,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 46,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 47,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 48,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'ROUND TWO 3',
    questions: [
      {
        id: 49,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 50,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 51,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 52,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 53,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 54,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'ROUND TWO 4',
    questions: [
      {
        id: 55,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 56,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 57,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 58,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 59,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 60,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'ROUND TWO 5',
    questions: [
      {
        id: 61,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 62,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 63,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 64,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 65,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 66,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
  {
    category: 'ROUND TWO ROUND TWO 6',
    questions: [
      {
        id: 67,
        value: 100,
        question: 'Question1?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 68,
        value: 200,
        question: 'Question2?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 69,
        value: 300,
        question: 'Question3?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 70,
        value: 400,
        question: 'Question4?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 71,
        value: 500,
        question: 'Question5?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
      {
        id: 72,
        value: 600,
        question: 'Question6?',
        answers: ['answer1', 'answer2', 'answer3', 'answer4'],
        correct_answer: 'answer1',
      },
    ],
  },
];
